projects/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.utils.translation import ugettext_lazy

import views

app_name = 'projects'
urlpatterns = [
    url(r'^create.html$', views.create, name='create'),
    url(r'^(?P<username>[\w-]+)/(?P<project_code>[\w-]+)/(?P<branch_code>[\w-]+)$', views.editor, name='project'),
    url(r'^public.html$', views.community, name='community'),
    url(r'^myprojects.html$', views.my_projects, name='my_projects'),
]

webide/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.utils.translation import ugettext_lazy

import views

app_name = 'webide'
urlpatterns = [
    # Plugins
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),

    # Index
    url(r'^$', views.index),
    url(r'^index.html$', views.index, name='index'),

    # Apps
    url(r'^public/', include('public.urls')),
    url(r'^project/', include('projects.urls')),
]


admin.site.site_header = ugettext_lazy('Propeller WebIDE admin')
admin.site.site_title = ugettext_lazy('Propeller WebIDE administration')

projects/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Project(models.Model):
    user = models.ForeignKey(User, related_name='projects')
    code = models.SlugField()
    name = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    last_change = models.DateTimeField(auto_now=True)
    public = models.BooleanField(default=False)
    active_branch = models.ForeignKey('Branch', related_name='project_active_branch', null=True)

    class Meta:
        unique_together = (('user', 'code'),)


class Branch(models.Model):
    project = models.ForeignKey(Project, related_name='branches')
    code = models.SlugField()
    name = models.CharField(max_length=255)
    head = models.ForeignKey('Revision', related_name='branch_head_revision', null=True)

    class Meta:
        unique_together = (('project', 'name'),)


class File(models.Model):
    previous = models.ForeignKey('File', related_name='new_file_revisions', null=True)
    path = models.CharField(max_length=1000, default='')
    filename = models.CharField(max_length=255)
    file = models.TextField()
    mime = models.CharField(max_length=255)
    deleted = models.BooleanField(default=False)


class Revision(models.Model):
    branch = models.ForeignKey(Branch, related_name='revisions')
    previous = models.ForeignKey('Revision', related_name='new_revisions', null=True)
    files = models.ManyToManyField(File, related_name='revisions')
    comment = models.TextField(null=True)
    committed = models.BooleanField(default=False)
    committed_at = models.DateTimeField(null=True)

projects/forms.py
from django import forms
from django.core.exceptions import ValidationError

from projects.models import Project


class CreateProjectForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(CreateProjectForm, self).__init__(*args, **kwargs)

    def clean_name(self):
        return self.cleaned_data['name'].strip()

    def clean_code(self):
        code = self.cleaned_data['code'].strip().lower().replace(' ', '_')
        if Project.objects.filter(user=self.user, code=code).exists():
            raise ValidationError('A project with this code already exists')
        return code

    class Meta:
        model = Project
        fields = ['name', 'code', 'public']


class CreateProjectFormBasic(forms.Form):
    name = forms.CharField(label='Name', max_length=255)
    code = forms.SlugField(label='Code', max_length=255)

    def clean_name(self):
        return self.cleaned_data['name'].strip()

    def clean_code(self):
        return self.cleaned_data['code'].strip().lower().replace(' ', '_')

projects/views.py
import logging

from django_tables2 import RequestConfig
from raven.contrib.django.raven_compat.models import client
import os

from django.conf import settings
from django.http import HttpResponseRedirect
from django.http import HttpResponseServerError
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from django.views.decorators.http import require_POST, require_GET

from projects.forms import CreateProjectForm
from projects.models import Project, Branch, Revision, File
from projects.tables import MyProjectsTable, PublicProjectTable

logger = logging.getLogger(__name__)


def create(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = CreateProjectForm(request.user, request.POST)
        # check whether it's valid:
        if form.is_valid():
            project = form.save(commit=False)
            project.user = request.user
            project.save()

            branch = Branch()
            branch.project = project
            branch.code = 'master'
            branch.name = 'Master'
            branch.save()

            project.active_branch = branch
            project.save()

            revision = Revision()
            revision.branch = branch
            revision.save()

            branch.head = revision
            branch.save()

            readme_file = File()
            readme_file.filename = 'README.md'
            readme_file.file = '# %s\n' % project.name
            readme_file.mime = 'text/markdown'
            readme_file.save()
            revision.files.add(readme_file)

            side_config_file = File()
            side_config_file.filename = '%s.side' % project.code
            side_config_file.file = '%s.c\n' % project.code
            side_config_file.mime = 'text/plain'
            side_config_file.save()
            revision.files.add(side_config_file)

            main_source_file = File()
            main_source_file.filename = '%s.c' % project.code
            main_source_file.file = """// ------ Libraries and Definitions ------
#include "simpletools.h"


// ------ Main Program ------
int main()
{
}
"""
            main_source_file.mime = 'text/x-c'
            main_source_file.save()
            revision.files.add(main_source_file)

            revision.save()

            return redirect('projects:project', project.user.username, project.code, 'master')
    # if a GET (or any other method) we'll create a blank form
    else:
        form = CreateProjectForm(request.user)

    logger.error("Project already exists")
    return render(request, 'create.html', {'form': form})


def editor(request, username, project_code, branch_code):
    project = get_object_or_404(Project, user__username=username, code=project_code)
    branch = get_object_or_404(Branch, project=project, code=branch_code)
    return render(request, 'editor.html', {
        'project': project,
        'branch': branch
    })


def community(request):
    queryset = Project.objects.filter(public=True)
    table = PublicProjectTable(queryset)
    RequestConfig(request, paginate={'per_page': 25}).configure(table)
    return render(request, 'community.html', {'table': table})


def my_projects(request):
    queryset = Project.objects.filter(user=request.user)
    table = MyProjectsTable(queryset)
    RequestConfig(request, paginate={'per_page': 25}).configure(table)
    return render(request, 'my_projects.html', {'table': table})

webide/views.py
from django.shortcuts import render, redirect


# Create your views here.
from projects.models import Project


def index(request):
    projects = Project.objects.order_by('-created')[:10]
    # load app
    return render(request, 'index.html', {'projects': projects})

projects/templates/community.html
{% extends 'base.html' %}

{% load django_tables2 %}

{% block content %}

    <h2>Community projects</h2>

    {% render_table table %}

{% endblock %}

projects/templates/create.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h1>Create new project</h1>

    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                Create
            </button>
        {% endbuttons %}
    </form>

{% endblock %}

projects/templates/editor.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
    {% if settings.USE_CDN %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css"/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/screenfull.js/3.2.0/screenfull.min.js"  type="text/javascript"></script>
    {% else %}
        <!-- TODO: local scripts -->
        <link rel="stylesheet" href="{% static 'libs/jstree/dist/themes/default/style.css' %}"/>
        <script src="{% static 'libs/jstree/dist/jstree.js' %}" type="text/javascript"
                charset="utf-8"></script>
        <script src="{% static 'libs/screenfull.js' %}" type="text/javascript"></script>
    {% endif %}

    <script src="{% static 'libs/ace/src-noconflict/ace.js' %}" type="text/javascript" charset="utf-8"></script>

    <link rel="stylesheet" href="{% static 'editor.css' %}"/>
    <script src="{% static 'editor.js' %}" type="text/javascript"
                charset="utf-8"></script>

{% endblock %}

{% block content-fluid %}


    <nav class="navbar navbar-default">
        <div class="container">
            <a class="navbar-brand" href="#">Project: {{ project.name }}</a>
        </div>
    </nav>

    <div id="editor">
        <div id="workspace">
            <div id="left-side-bar" class="sidebar collapsed">
                <div class="sidebar-title"><h4>Project explorer</h4></div>
                <div class="sidebar-content">
                    <div id="project-file-tree">
                        <ul>
                            {% for file in project.active_branch.head.files.all %}
                                <li><a href="#{{ file.filename }}">{{ file.filename }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            <div id="screen">
                <div id="main-editor" class="widget-container width-12">
                    <div class="widget">
                        <div class="widget-title"><h4>Editor: <span id="main-editor-filename"
                                                                    class="filename">file.c</span></h4></div>
                        <div class="widget-content">
                            <div id="ace-main-editor" class="ace-editor">Hallo</div>
                        </div>
                    </div>
                </div>
                <div id="second-editor" class="widget-container width-6 hidden">
                    <div class="widget">
                        <div class="widget-title"><h4>Editor: <span id="second-editor-filename"
                                                                    class="filename">file.h</span></h4></div>
                        <div class="widget-content">
                            <div id="ace-second-editor" class="ace-editor"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="right-side-bar" class="sidebar collapsed">
                <div class="sidebar-title"><h4>Serial terminal</h4></div>
                <div class="sidebar-content">
                    Baud rate
                </div>
            </div>
        </div>

        <div id="compile-log" class="widget collapsed">
            <div class="widget">
                <div class="widget-title"><h4>Compile log</h4></div>
                <div class="widget-content">Hallo</div>
            </div>

        </div>
    </div>

{% endblock %}

projects/templates/list.html
{% extends 'base.html' %}

{% block content %}

    <h2>Your projects</h2>

    <ul id="project-list">

    </ul>

{% endblock %}

projects/templates/my_projects.html
{% extends 'base.html' %}

{% load django_tables2 %}

{% block content %}

    <h2>My projects</h2>

    {% render_table table %}

{% endblock %}

projects/templates/project.html
{% extends 'base.html' %}

{% block content %}

    <h2>Project</h2>



{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">

    {% if settings.USE_CDN %}
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <link href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"
              type="text/css">
    {% else %}
        <!-- TODO: local scripts -->
    {% endif %}

<link href="{% static 'style.css' %}" rel="stylesheet"
              type="text/css">

    {% block head %}{% endblock %}
    <title>{% block title %}Propeller WebIDE{% endblock %}</title>
</head>
<body>


<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" id="nav-logo" href="/"><strong>BETA</strong> Propeller WebIDE</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'projects:community' %}">Community projects</a></li>

                {% if user.is_authenticated %}
                    <li><a href="{% url 'projects:my_projects' %}">My projects</a></li>
                    <li><a href="{% url 'projects:create' %}">New project</a></li>
                {% endif %}
            </ul>


            <ul class="nav navbar-nav navbar-right">

                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-haspopup="true">{{ user.username }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/blockly/profile">Profile</a></li>
                            <!--     <li><a href="/blockly/public/profile">Public profile</a></li> -->
                            <li><a href="{% url 'account_logout' %}">Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'account_login' %}">Login</a></li>
                    <li><a href="{% url 'account_signup' %}">Register</a></li>
                {% endif %}


                <li class="navbar-text">
                    <form style="margin-bottom: 0;">
                        <select id="language" name="language" onchange="submit()">
                            <option value="en">English</option>

                        </select>
                    </form>
                </li>

                <li id="fullscreen" class="hidden">
                    <a href="#"><span class="glyphicon glyphicon-fullscreen"></span></a>
                </li>
            </ul>

        </div>
    </div>
</nav>


<div class="container">

    {% block content %}{% endblock %}
</div>

{% block content-fluid %}{% endblock %}



    <footer class="footer">
        <nav class="navbar">
            <div class="container">
                <div>
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'public:license' %}">License</a></li>
                        <li><a href="{% url 'public:changelog' %}">Change log</a></li>
                        <li><a href="{% url 'public:libraries' %}">External libraries</a></li>
                        <li><a href="{% url 'public:communicator-download' %}">Communicator download</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">

                        <li><a href="http://www.parallax.com" target="_blank">
                            V0.96.383
                            Parallax &copy; 2016 - {% now 'Y' %}</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </footer>
</body>
</html>

templates/ultra-base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% comment %}
    For:
    - Favicon
    - Search meta
    - ...
    {% endcomment %}
    {% block head %}{% endblock %}
    <title>{% block title %}Propeller WebIDE{% endblock %}</title>
</head>
<body>

{% block body %}{% endblock %}

</body>
</html>

webide/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Propeller WebIDE</h1>

    <p>Introduction text</p>

    {% if user.is_authenticated %}
        <a href="{% url 'projects:create' %}">Create new project</a>

        <h2>Your latest projects</h2>
        <ul id="project-list">
            {% for project in projects %}
                <li><a href="{% url 'projects:project' project.user.username project.code %}">{{ project.name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

{% endblock %}